version: '3'

networks:
  main:

services:
  build-war:
    image: maven:3.3.9-jdk-8
    networks:
      - main
    working_dir: /app
    volumes:
      - ./api:/app
    command: mvn package

  api:
    image: api
    build: ./api
    networks:
      - main
    ports:
      - 8080:8080
    volumes:
      - ./api/target/api-0.1.0.war:/usr/local/tomcat/webapps/ROOT.war
